### ISSUE TITLE
Add advice on using mouse to move cursor

### ISSUE THREAD

**Issue by nkrabben** [dd388/crals#12]
A lot of the commands here are fairly long and have sections that need to be edited like source and destination directories.

I think it would be useful to have directions about using the mouse to move cursor. I know on Terminal and ZSH on Macs you can do this by pressing alt/option and clicking where you want the cursor to go. Is this universal enough on other consoles that we can add instructions for it?

Another option could be some of the basic cursor movement commands like ctrl+a and ctrl+e
https://www.gnu.org/software/bash/manual/html_node/Commands-For-Moving.html

**Comment by kieranjol** [comment]
It isn't possible on windows terminals as far as I know, but I think that its inclusion is really worthwhile as it makes the command line so much easier to use on OSX. Same with CTRL+ A/E.

**Comment by dd388** [comment]
I had originally put in the section "Add helpful flags into bash shell scripts" for the end, but maybe that heading can be edited like, just overall helpful miscellany? I think as long as the site is organized logically, anything that makes the command line easier should be included.

**Comment by nkrabben** [comment]
Took a swing at this by adding another section at the bottom.
https://nkrabben.github.io/crals/

Thoughts?

**Comment by dd388** [comment]
I think it's great. One minor minor edit: "Move around on the command line"

What do you think?

**Comment by nkrabben** [comment]
Sounded good... and then I forgot to add the "the". Can you edit that in?

**Comment by dd388** [comment]
I don't see the missing "the" ...

**Comment by nkrabben** [comment]
Sorry, I meant the "on" is missing. You suggested
"Move around on the command line"
and I committed
"Move around the command line"

Can you patch that?

**Comment by dd388** [comment]
Aha, yes.

**Comment by dd388** [comment]
Fixed.
