### ISSUE TITLE
Add bash history storage increase command

### ISSUE THREAD

**Issue by nkrabben** [dd388/crals#21]
The command we're building in https://github.com/dd388/crals/issues/18 can be more useful with more commands stored in the history. The problem is, is that this gets kind of shell-specific. I'll make a PR for bash since that should cover the base case, but it will probably need more shells over time.

**Comment by ablwr** [comment]
🐚 🐚 🐚 🐚 🐚 🐚 🐚 🐚 🐚 🐚 🐚 🐚

**Comment by dd388** [comment]
Rock on!
