### ISSUE TITLE
Rename WAV files by substituting one string for another within the existing filename

### ISSUE THREAD

**Issue by bertramlyons** [dd388/crals#6]
for i in *.wav; do mv “$i” “$(echo $i | sed ’s/_MAC_/_MN_/g’)”; done

This is a supplement to the command to append file extensions. This works within the full filename string, instead of only at the beginning or end. It uses “sed” to do this substitution work. The ‘s’ tells sed that we want it to perform a substitution. The "/" characters serve as separators between the old and new values we want to find/replace. First we define the old value we want to replace. In this case “_MAC_”. Then we define the new value we want to substitute for the old value. In this case “_MN_”. The ‘g’ tells sed that we want it to do this globally in the string, i.e., every time it sees _MAC_ it replaces with _MN_. It is essentially a find and replace action.
- Bert

**Comment by dd388** [comment]
This is great. I'll get it added to the site as soon as I'm able. Thank you!

**Comment by dd388** [comment]
Added! https://github.com/dd388/crals/commit/d9af6a156e5784c5bd10ff294ccd3e91ffda89cf
