### ISSUE TITLE
List all files/folders and write out to external text file

### ISSUE THREAD

**Issue by bertramlyons** [dd388/crals#7]
ls -alR /set/your/path/here > /set/your/output/path/inventory.txt

This is great way to extract a list of files/directories (as well as filesystem data about the files/directories) to a "space" separated text file that you can parse separately from the CLI interface.
- Bert

**Comment by dd388** [comment]
Also excellent. Thanks for the suggestion!

**Comment by dd388** [comment]
Added via https://github.com/dd388/crals/commit/a7d9241f1facfd9a94e6eeec1f98acfe946538f8
