### ISSUE TITLE
More examples from AMIA training

### ISSUE THREAD

**Issue by dd388** [dd388/crals#9]
Adding in more examples from presentations at AMIA

**Comment by ablwr** [comment]
Oh, I can't self-assign this either... I thought since I'd historically contributed that it'd allow it. I think I'd have to be added as a member in settings. Meh, anyway, will put this on my todo list.

**Comment by dd388** [comment]
This is a note to remind myself to add you to the project tomorrow.

**Comment by ablwr** [comment]
Other training involved a much longer script that hasn't been shared out yet and another talk that was slightly higher-level -- working through figuring out workflows!

**Comment by dd388** [comment]
OK, cool. I can close this for now and we can open up another ticket if other examples come in. Thank you!
